---
title: "RSP analysis"
author: "Katie L. Duggan DiDominic"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load packages
```{r}
#install.packages("tidyverse")
library(tidyverse)
#install.packages("NatParksPalettes")
library(NatParksPalettes)
```

## Load data
```{r}
rspdata <- read_csv(file = "/Users/u4rrnkld/OneDrive - US Army Corps of Engineers/Documents/RSPtoCBR_correlation/data/rspdata.csv")

cbrdata <- read_csv(file = "/Users/u4rrnkld/OneDrive - US Army Corps of Engineers/Documents/RSPtoCBR_correlation/data/cbrdata.csv")

meancbrdata <- read_csv(file = "/Users/u4rrnkld/OneDrive - US Army Corps of Engineers/Documents/RSPtoCBR_correlation/data/meancbrdata.csv") %>% 
  select(c(station_test, hours_avg, CBR))
```

## Analyze

### Spaghetti plots
```{r}
# Create a small dataframe for your segment(s)
segment_data <- data.frame(
  x = c(99, 65),
  xend = c(99, 65),
  y = c(0, 250),
  yend = c(250, 400),
  segment_label = "500,000 lbs")  # label that will show in the legend

segment_data$sample_id <- NA

#### plot (used in TR)
rspdata %>% 
  mutate(CBR_rep = paste(CBR_id, rep)) %>% 
  ggplot(aes(x = rsp_index, y = depth_from_surface, group = sample_id, color = CBR_id)) +
  geom_path(linewidth = 0.75) +
  geom_segment(data = segment_data,
               aes(x = x, xend = xend, y = y, yend = yend, linetype = segment_label),
               color = "black",
               inherit.aes = FALSE,
               linewidth = 0.75) +
  scale_linetype_manual(name = "Minimum Required \nRSP for Aircraft Load",
                        values = c("500,000 lbs" = "solid")) +
  scale_color_manual(values = natparks.pals("Yellowstone", 5)) +
  facet_grid(station~test, switch = "x") +
  scale_y_continuous(trans = "reverse") +
  scale_x_continuous(position = "top") +
  xlab("RSP Index") +
  ylab("Depth from Surface (mm)") +
  labs(color = "Corresponding\nCBR Test\nLocation") +
  theme_bw() +
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        strip.text = element_text(size = 15))

#### points with mean RSP lines - used to get one mean RSP for each station/test combo
vlines_df <- rspdata %>%
  #group_by(cbr_id) %>%
  group_by(station_test) %>%
  summarize(mean_rsp = mean(rsp_index)) %>% 
  mutate(station = str_sub(station_test, 1, 4)) %>% 
  mutate(test = str_sub(station_test, 6, 10)) %>%
  mutate(test = ifelse(test == "test0", "Test 0", test)) %>% 
  mutate(test = ifelse(test == "test1", "Test 1", test)) %>% 
  mutate(test = ifelse(test == "test2", "Test 2", test)) %>% 
  mutate(test = ifelse(test == "test3", "Test 3", test)) %>% 
  mutate(test = ifelse(test == "test4", "Test 4", test)) %>% 
  mutate(test = ifelse(test == "test5", "Test 5", test))

rspdata %>% 
  mutate(CBR_rep = paste(CBR_id, rep)) %>% 
  ggplot(aes(x = rsp_index, y = depth_from_surface, group = CBR_id, color = CBR_id)) +
  #geom_path(linewidth = 0.75) +
  geom_point() +
  geom_vline(data = vlines_df, aes(xintercept = mean_rsp), color = "black", linetype = "dashed", linewidth = 1) +
  #scale_linetype_manual(name = "Minimum Required \nRSP for Aircraft Load",
                        #values = c("500,000 lbs" = "solid")) +
  scale_color_manual(values = natparks.pals("Yellowstone", 5)) +
  facet_grid(station~test, switch = "x") +
  scale_y_continuous(trans = "reverse") +
  scale_x_continuous(position = "top") +
  xlab("RSP Index") +
  ylab("Depth from Surface (mm)") +
  labs(color = "Corresponding\nCBR") +
  theme_bw() +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        strip.text = element_text(size = 12))

#### STEPwise version of previous plot
rspdata %>% 
  mutate(CBR_rep = paste(CBR_id, rep)) %>% 
  ggplot(aes(x = depth_from_surface, y = rsp_index, group = sample_id, color = CBR_id)) +
  geom_step(linewidth = 0.75, direction = "vh") +
  scale_color_manual(values = natparks.pals("Yellowstone", 5)) +
  facet_grid(station~test, switch = "x") +
  scale_x_continuous(trans = "reverse") +
  scale_y_continuous(position = "right") +
  coord_flip() +
  xlab("Depth from Surface (mm)") +
  ylab("RSP Index") +
  labs(color = "Corresponding\nCBR") +
  theme_bw() +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        strip.text = element_text(size = 12))

#### plot - each CBR and each test (colored by station)
colors <- natparks.pals("Yellowstone", 5)
selected_colors <- colors[c(1, 3, 4)]

rspdata %>% ## stepwise station vs station grid
  filter(station == "STA1") %>% 
  #filter(rep == "r1") %>% 
  mutate(CBR_rep = paste(CBR_id, rep)) %>% 
  ggplot(aes(x = depth_from_surface, y = rsp_index, group = sample_id, color = rep)) +
  #geom_path(linewidth = 0.75) +
  geom_step(linewidth = 0.75, direction = "vh") +
  #geom_segment(aes(x = 99, y = 0, xend = 99, yend = 250), color = "black", , linewidth = 1) +
  #geom_segment(aes(x = 65, y = 250, xend = 65, yend = 400), color = "black", linewidth = 1) +
  scale_color_manual(values=selected_colors) +
  #scale_color_manual(values = natparks.pals("Yellowstone", 5)) +
  facet_grid(CBR_id~test, switch = "x") +
  scale_x_continuous(trans = "reverse") +
  scale_y_continuous(position = "right") +
  coord_flip() +
  xlab("Depth from Surface (mm)") +
  ylab("RSP Index") +
  labs(color = "Corresponding\nCBR") +
  theme_bw() +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        strip.text = element_text(size = 12))

## average spaghetti plot for each time point (test #)
cbr_avg <- rspdata %>% 
  select(c(sample_id, depth_from_surface, rsp_index)) %>% 
  pivot_wider(names_from = sample_id, values_from = rsp_index) %>% 
  arrange(depth_from_surface) %>% 
  mutate(STA1_test0 = round(rowMeans(across(starts_with("STA1_test0")), na.rm=TRUE))) %>% 
  mutate(STA2_test0 = round(rowMeans(across(starts_with("STA2_test0")), na.rm=TRUE))) %>% 
  mutate(STA1_test1 = round(rowMeans(across(starts_with("STA1_test1")), na.rm=TRUE))) %>% 
  mutate(STA2_test1 = round(rowMeans(across(starts_with("STA2_test1")), na.rm=TRUE))) %>%
  mutate(STA1_test2 = round(rowMeans(across(starts_with("STA1_test2")), na.rm=TRUE))) %>% 
  mutate(STA2_test2 = round(rowMeans(across(starts_with("STA2_test2")), na.rm=TRUE))) %>%
  mutate(STA1_test3 = round(rowMeans(across(starts_with("STA1_test3")), na.rm=TRUE))) %>% 
  mutate(STA2_test3 = round(rowMeans(across(starts_with("STA2_test3")), na.rm=TRUE))) %>%
  mutate(STA1_test4 = round(rowMeans(across(starts_with("STA1_test4")), na.rm=TRUE))) %>% 
  mutate(STA2_test4 = round(rowMeans(across(starts_with("STA2_test4")), na.rm=TRUE))) %>%
  select(c(STA1_test0, STA2_test0, STA1_test1, STA2_test1, STA1_test2, STA2_test2, STA1_test3, STA2_test3, STA1_test4, STA2_test4, depth_from_surface)) %>% 
  pivot_longer(cols = c(STA1_test0, STA2_test0, STA1_test1, STA2_test1, STA1_test2, STA2_test2, STA1_test3, STA2_test3, STA1_test4, STA2_test4), names_to = "station_test", values_to = "rsp_index") %>% 
  mutate(station = substr(station_test, 1, 4)) %>% 
  mutate(test = substr(station_test, 6, 10))

#### plot
cbr_avg %>% 
  mutate(test = ifelse(test == "test0", "Test 0", test)) %>% 
  mutate(test = ifelse(test == "test1", "Test 1", test)) %>% 
  mutate(test = ifelse(test == "test2", "Test 2", test)) %>% 
  mutate(test = ifelse(test == "test3", "Test 3", test)) %>% 
  mutate(test = ifelse(test == "test4", "Test 4", test)) %>% 
  mutate(test = ifelse(test == "test5", "Test 5", test)) %>% 
  ggplot(aes(x = rsp_index, y = depth_from_surface, group = station_test, color = test)) +
  geom_path(linewidth = 0.75) +
  #scale_color_manual(values = test_colors) +
  scale_color_manual(values=natparks.pals("Yellowstone", 5)) +
  facet_grid(~station, switch = "x") +
  scale_y_continuous(trans = "reverse") +
  scale_x_continuous(position = "top") +
  xlab("Average RSP Index") +
  ylab("Depth from Surface (mm)") +
  labs(color = "Corresponding\nCBR Timepoint") +
  theme_bw()

####### plot of mean RSPs (all data)
mean_rsp_cbr <- full_join(meancbrdata, vlines_df, by = "station_test")

mean_rsp_cbr %>% 
  ggplot(aes(x = hours_avg, y = mean_rsp, group = station, color = station)) +
  geom_line(linewidth = 1) +
  scale_color_manual(values = selected_colors) +
  xlab("Time since Test 0 (hours)") +
  ylab("Mean RSP across depth (0-400mm)") +
  labs(color = "Test Station") +
  theme_bw() +
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        strip.text = element_text(size = 15))
```

### Correlation attempt with mean RSP from points (10 to 10, CBR to RSP)
```{r}
rsp_means_for_corr <- rspdata %>% #filter for RSPs relating to the CBRs that Margie kept
  filter(!(station == "STA1" & test == "Test 0" & CBR_id == "CBR4")) %>% # remove CBR4 for STA1/test0
  filter(!(station == "STA1" & test == "Test 1" & CBR_id == "CBR3")) %>% # remove CBR3 for STA1/test1
  filter(!(station == "STA1" & test == "Test 1" & CBR_id == "CBR4")) %>% # remove CBR4 for STA1/test1
  filter(!(station == "STA1" & test == "Test 2" & CBR_id == "CBR1")) %>% # remove CBR1 for STA1/test2
  filter(!(station == "STA1" & test == "Test 3" & CBR_id == "CBR3")) %>% # remove CBR3 for STA1/test3
  filter(!(station == "STA2" & test == "Test 2" & CBR_id == "CBR1")) %>% # remove CBR1 for STA2/test2
  filter(between(depth_from_surface, 50, 200)) %>% #keep 50mm through 200mm)
  group_by(station_test) %>%
  summarize(mean_rsp = mean(rsp_index)) %>% 
  mutate(station = str_sub(station_test, 1, 4)) %>% 
  mutate(test = str_sub(station_test, 6, 10)) %>%
  mutate(test = ifelse(test == "test0", "Test 0", test)) %>% 
  mutate(test = ifelse(test == "test1", "Test 1", test)) %>% 
  mutate(test = ifelse(test == "test2", "Test 2", test)) %>% 
  mutate(test = ifelse(test == "test3", "Test 3", test)) %>% 
  mutate(test = ifelse(test == "test4", "Test 4", test)) %>% 
  mutate(test = ifelse(test == "test5", "Test 5", test))

means_for_corr <- full_join(meancbrdata, rsp_means_for_corr, by = "station_test")

means_for_corr %>% ## only those relating to remaining CBR data
  ggplot(aes(x = hours_avg, y = mean_rsp, group = station, color = station)) +
  geom_line(linewidth = 1) +
  scale_color_manual(values = selected_colors) +
  xlab("Time since Test 0 (hours)") +
  ylab("Mean RSP across depth (0-400mm)") +
  labs(color = "Test Station") +
  theme_bw() +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        strip.text = element_text(size = 12))

## correlation
model <- lm(CBR ~ mean_rsp, data = means_for_corr)
r2 <- summary(model)$r.squared

ggplot(means_for_corr, aes(x = mean_rsp, y = CBR)) +
  geom_point(aes(color = station), size = 3) +
  #scale_x_log10() +
  #scale_y_log10() +
  scale_color_manual(values = selected_colors) +
  geom_smooth(method = "lm", se = FALSE, color = "black", linetype = "dashed") +
  annotate("text", x = 35, y = 18, label = paste("R² =", round(r2, 2)), size = 6, hjust = 4) +
  xlab("RSP") +
  ylab("CBR") +
  labs(color = "Test Station:") +
  theme_bw() +
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.position = "top",
        strip.text = element_text(size = 15))
```



-----------------------------------------------

### Filter correlation data (top 6 inches and CBRs Margie kept)
```{r}
## top 6 inches and CBRs that Margie kept
surface_CBR <- rspdata %>%
  filter(!depth_from_surface > 150) %>% #top 6 inches (~150mm)
  filter(!(station == "STA1" & test == "Test 0" & CBR_id == "CBR4")) %>% # remove CBR4 for STA1/test0
  filter(!(station == "STA1" & test == "Test 1" & CBR_id == "CBR3")) %>% # remove CBR3 for STA1/test1
  filter(!(station == "STA1" & test == "Test 1" & CBR_id == "CBR4")) %>% # remove CBR4 for STA1/test1
  filter(!(station == "STA1" & test == "Test 2" & CBR_id == "CBR1")) %>% # remove CBR1 for STA1/test2
  filter(!(station == "STA1" & test == "Test 3" & CBR_id == "CBR3")) %>% # remove CBR3 for STA1/test3
  filter(!(station == "STA2" & test == "Test 2" & CBR_id == "CBR1")) # remove CBR1 for STA2/test2

#### plot
surface_CBR %>% 
  ggplot(aes(x = rsp_index, y = depth_from_surface, group = sample_id, color = CBR_id)) +
  geom_path(linewidth = 0.75) +
  scale_color_manual(values=natparks.pals("Yellowstone", 5)) +
  facet_grid(station~test, switch = "x") +
  scale_y_continuous(trans = "reverse", limits = c(150,0)) +
  scale_x_continuous(position = "top") +
  xlab("RSP Index at Surface (0-6 inches)") +
  ylab("Depth from Surface (mm)") +
  labs(color = "Corresponding\nCBR") +
  theme_bw()

## average for each time point (test #) in top 6 inches
method1 <- surface_CBR %>% 
  select(c(sample_id, depth_from_surface, rsp_index)) %>% 
  pivot_wider(names_from = sample_id, values_from = rsp_index) %>% 
  arrange(depth_from_surface) %>% 
  mutate(STA1_test0 = round(rowMeans(across(starts_with("STA1_test0")), na.rm=TRUE))) %>% 
  mutate(STA2_test0 = round(rowMeans(across(starts_with("STA2_test0")), na.rm=TRUE))) %>% 
  mutate(STA1_test1 = round(rowMeans(across(starts_with("STA1_test1")), na.rm=TRUE))) %>% 
  mutate(STA2_test1 = round(rowMeans(across(starts_with("STA2_test1")), na.rm=TRUE))) %>%
  mutate(STA1_test2 = round(rowMeans(across(starts_with("STA1_test2")), na.rm=TRUE))) %>% 
  mutate(STA2_test2 = round(rowMeans(across(starts_with("STA2_test2")), na.rm=TRUE))) %>%
  mutate(STA1_test3 = round(rowMeans(across(starts_with("STA1_test3")), na.rm=TRUE))) %>% 
  mutate(STA2_test3 = round(rowMeans(across(starts_with("STA2_test3")), na.rm=TRUE))) %>%
  mutate(STA1_test4 = round(rowMeans(across(starts_with("STA1_test4")), na.rm=TRUE))) %>% 
  mutate(STA2_test4 = round(rowMeans(across(starts_with("STA2_test4")), na.rm=TRUE))) %>%
  select(c(STA1_test0, STA2_test0, STA1_test1, STA2_test1, STA1_test2, STA2_test2, STA1_test3, STA2_test3, STA1_test4, STA2_test4, depth_from_surface)) %>% 
  pivot_longer(cols = c(STA1_test0, STA2_test0, STA1_test1, STA2_test1, STA1_test2, STA2_test2, STA1_test3, STA2_test3, STA1_test4, STA2_test4), names_to = "station_test", values_to = "rsp_index") %>% 
  mutate(station = substr(station_test, 1, 4)) %>% 
  mutate(test = substr(station_test, 6, 10)) %>% 
  mutate(test = ifelse(test == "test0", "Test 0", test)) %>% 
  mutate(test = ifelse(test == "test1", "Test 1", test)) %>% 
  mutate(test = ifelse(test == "test2", "Test 2", test)) %>% 
  mutate(test = ifelse(test == "test3", "Test 3", test)) %>% 
  mutate(test = ifelse(test == "test4", "Test 4", test)) %>% 
  mutate(test = ifelse(test == "test5", "Test 5", test))

#### plot
method1 %>% 
  ggplot(aes(x = rsp_index, y = depth_from_surface, group = station_test, color = test)) +
  geom_path(linewidth = 0.75) +
  scale_color_manual(values = test_colors) +
  facet_grid(~station, switch = "x") +
  scale_y_continuous(trans = "reverse", limits = c(150,0)) +
  scale_x_continuous(position = "top") +
  xlab("Average RSP Index at Surface (0-6 inches)") +
  ylab("Depth from Surface (mm)") +
  labs(color = "Corresponding\nCBR Timepoint") +
  theme_bw()

## method 2
method2 <- surface_CBR %>% 
  select(c(sample_id, depth_from_surface, rsp_index)) %>% 
  pivot_wider(names_from = sample_id, values_from = rsp_index) %>% 
  arrange(depth_from_surface) %>% 
  mutate(STA1_test0_CBR1 = round(rowMeans(across(starts_with("STA1_test0_CBR1")), na.rm=TRUE))) %>% 
  mutate(STA1_test0_CBR2 = round(rowMeans(across(starts_with("STA1_test0_CBR2")), na.rm=TRUE))) %>%
  mutate(STA1_test0_CBR3 = round(rowMeans(across(starts_with("STA1_test0_CBR3")), na.rm=TRUE))) %>%
  mutate(STA2_test0_CBR1 = round(rowMeans(across(starts_with("STA2_test0_CBR1")), na.rm=TRUE))) %>% 
  mutate(STA2_test0_CBR2 = round(rowMeans(across(starts_with("STA2_test0_CBR2")), na.rm=TRUE))) %>%
  mutate(STA2_test0_CBR3 = round(rowMeans(across(starts_with("STA2_test0_CBR3")), na.rm=TRUE))) %>%
  mutate(STA1_test1_CBR1 = round(rowMeans(across(starts_with("STA1_test1_CBR1")), na.rm=TRUE))) %>% 
  mutate(STA1_test1_CBR2 = round(rowMeans(across(starts_with("STA1_test1_CBR2")), na.rm=TRUE))) %>%
  mutate(STA1_test1_CBR5 = round(rowMeans(across(starts_with("STA1_test1_CBR5")), na.rm=TRUE))) %>%
  mutate(STA2_test1_CBR1 = round(rowMeans(across(starts_with("STA2_test1_CBR1")), na.rm=TRUE))) %>% 
  mutate(STA2_test1_CBR2 = round(rowMeans(across(starts_with("STA2_test1_CBR2")), na.rm=TRUE))) %>%
  mutate(STA2_test1_CBR3 = round(rowMeans(across(starts_with("STA2_test1_CBR3")), na.rm=TRUE))) %>%
  mutate(STA1_test2_CBR2 = round(rowMeans(across(starts_with("STA1_test2_CBR2")), na.rm=TRUE))) %>% 
  mutate(STA1_test2_CBR3 = round(rowMeans(across(starts_with("STA1_test2_CBR3")), na.rm=TRUE))) %>%
  mutate(STA1_test2_CBR4 = round(rowMeans(across(starts_with("STA1_test2_CBR4")), na.rm=TRUE))) %>%
  mutate(STA2_test2_CBR2 = round(rowMeans(across(starts_with("STA2_test2_CBR2")), na.rm=TRUE))) %>% 
  mutate(STA2_test2_CBR3 = round(rowMeans(across(starts_with("STA2_test2_CBR3")), na.rm=TRUE))) %>%
  mutate(STA2_test2_CBR4 = round(rowMeans(across(starts_with("STA2_test2_CBR4")), na.rm=TRUE))) %>%
  mutate(STA1_test3_CBR1 = round(rowMeans(across(starts_with("STA1_test3_CBR1")), na.rm=TRUE))) %>% 
  mutate(STA1_test3_CBR2 = round(rowMeans(across(starts_with("STA1_test3_CBR2")), na.rm=TRUE))) %>%
  mutate(STA1_test3_CBR4 = round(rowMeans(across(starts_with("STA1_test3_CBR4")), na.rm=TRUE))) %>%
  mutate(STA2_test3_CBR1 = round(rowMeans(across(starts_with("STA2_test3_CBR1")), na.rm=TRUE))) %>% 
  mutate(STA2_test3_CBR2 = round(rowMeans(across(starts_with("STA2_test3_CBR2")), na.rm=TRUE))) %>%
  mutate(STA2_test3_CBR3 = round(rowMeans(across(starts_with("STA2_test3_CBR3")), na.rm=TRUE))) %>%
  mutate(STA1_test4_CBR1 = round(rowMeans(across(starts_with("STA1_test4_CBR1")), na.rm=TRUE))) %>% 
  mutate(STA1_test4_CBR2 = round(rowMeans(across(starts_with("STA1_test4_CBR2")), na.rm=TRUE))) %>%
  mutate(STA1_test4_CBR3 = round(rowMeans(across(starts_with("STA1_test4_CBR3")), na.rm=TRUE))) %>%
  mutate(STA2_test4_CBR1 = round(rowMeans(across(starts_with("STA2_test4_CBR1")), na.rm=TRUE))) %>% 
  mutate(STA2_test4_CBR2 = round(rowMeans(across(starts_with("STA2_test4_CBR2")), na.rm=TRUE))) %>%
  mutate(STA2_test4_CBR3 = round(rowMeans(across(starts_with("STA2_test4_CBR3")), na.rm=TRUE))) %>%
  select(c(STA1_test0_CBR1, STA1_test0_CBR2, STA1_test0_CBR3, STA2_test0_CBR1, STA2_test0_CBR2, STA2_test0_CBR3, STA1_test1_CBR1, STA1_test1_CBR2, STA1_test1_CBR5, STA2_test1_CBR1, STA2_test1_CBR2, STA2_test1_CBR3, STA1_test2_CBR2, STA1_test2_CBR3, STA1_test2_CBR4, STA2_test2_CBR2, STA2_test2_CBR3, STA2_test2_CBR4, STA1_test3_CBR1, STA1_test3_CBR2, STA1_test3_CBR4, STA2_test3_CBR1, STA2_test3_CBR2, STA2_test3_CBR3, STA1_test4_CBR1, STA1_test4_CBR2, STA1_test4_CBR3, STA2_test4_CBR1, STA2_test4_CBR2, STA2_test4_CBR3, depth_from_surface)) %>% 
  pivot_longer(cols = c(STA1_test0_CBR1, STA1_test0_CBR2, STA1_test0_CBR3, STA2_test0_CBR1, STA2_test0_CBR2, STA2_test0_CBR3, STA1_test1_CBR1, STA1_test1_CBR2, STA1_test1_CBR5, STA2_test1_CBR1, STA2_test1_CBR2, STA2_test1_CBR3, STA1_test2_CBR2, STA1_test2_CBR3, STA1_test2_CBR4, STA2_test2_CBR2, STA2_test2_CBR3, STA2_test2_CBR4, STA1_test3_CBR1, STA1_test3_CBR2, STA1_test3_CBR4, STA2_test3_CBR1, STA2_test3_CBR2, STA2_test3_CBR3, STA1_test4_CBR1, STA1_test4_CBR2, STA1_test4_CBR3, STA2_test4_CBR1, STA2_test4_CBR2, STA2_test4_CBR3), names_to = "station_test_CBR", values_to = "rsp_index") %>% 
  mutate(station = substr(station_test_CBR, 1, 4)) %>% 
  mutate(test = substr(station_test_CBR, 6, 10)) %>% 
  mutate(test = ifelse(test == "test0", "Test 0", test)) %>% 
  mutate(test = ifelse(test == "test1", "Test 1", test)) %>% 
  mutate(test = ifelse(test == "test2", "Test 2", test)) %>% 
  mutate(test = ifelse(test == "test3", "Test 3", test)) %>% 
  mutate(test = ifelse(test == "test4", "Test 4", test)) %>% 
  mutate(test = ifelse(test == "test5", "Test 5", test))

method2 %>% 
  ggplot(aes(x = rsp_index, y = depth_from_surface, group = station_test_CBR, color = test)) +
  geom_path(linewidth = 0.75) +
  scale_color_manual(values = test_colors) +
  facet_grid(~station, switch = "x") +
  scale_y_continuous(trans = "reverse", limits = c(150,0)) +
  scale_x_continuous(position = "top") +
  xlab("Average RSP Index at Surface (0-6 inches)") +
  ylab("Depth from Surface (mm)") +
  labs(color = "Corresponding\nCBR Timepoint") +
  theme_bw()
```

#### For correlation
```{r}
meanCBR <- cbrdata %>% 
  group_by(station_test) %>% 
  summarize(meanCBR = mean(CBR))

## Method 1: top  6 inches, Margie's CBR avg, and avg RSP across depth
method1_corrval <- method1 %>% #average per test and averaged across depth too
  group_by(station_test) %>% 
  summarize(meanRSP = mean(rsp_index, na.rm = TRUE)) %>% 
  full_join(meanCBR, by = "station_test")

model1 <- lm(meanRSP ~ meanCBR, data = method1_corrval)
r2_1 <- summary(model1)$r.squared

method1_corrval %>% 
  ggplot(aes(x = meanRSP, y = meanCBR)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  annotate("text", x = 35, y = 18, label = paste("R² =", round(r2_1, 2)), size = 5, hjust = 1)

## Method 2: top 6 inches, Margie's CBR, and avg RSP across depth (1 avg RSP per CBR)
method2_corrval <- method2 %>% 
  group_by(station_test_CBR) %>% 
  summarize(meanRSP = mean(rsp_index, na.rm = TRUE)) %>% 
  full_join(cbrdata, by = "station_test_CBR")

model2 <- lm(meanRSP ~ CBR, data = method2_corrval)
r2_2 <- summary(model2)$r.squared

method2_corrval %>% 
  ggplot(aes(x = meanRSP, y = CBR)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  annotate("text", x = 28, y = 20, label = paste("R² =", round(r2_2, 2)), size = 5, hjust = 1)
```

### Filter correlation data (exclude 0/25mm and extend to 200mm, and CBRs Margie kept)
```{r}
## 50-200mm and CBRs that Margie kept
midlayers_mCBR <- rspdata %>%
  filter(between(depth_from_surface, 50, 200)) %>% #keep 50mm through 200mm)
  filter(!(test_area == "STA1" & test_id == "Test 0" & CBR_id == "CBR4")) %>% # remove CBR4 for STA1/test0
  filter(!(test_area == "STA1" & test_id == "Test 1" & CBR_id == "CBR3")) %>% # remove CBR3 for STA1/test1
  filter(!(test_area == "STA1" & test_id == "Test 1" & CBR_id == "CBR4")) %>% # remove CBR4 for STA1/test1
  filter(!(test_area == "STA1" & test_id == "Test 2" & CBR_id == "CBR1")) %>% # remove CBR1 for STA1/test2
  filter(!(test_area == "STA1" & test_id == "Test 3" & CBR_id == "CBR3")) %>% # remove CBR3 for STA1/test3
  filter(!(test_area == "STA2" & test_id == "Test 2" & CBR_id == "CBR1")) # remove CBR1 for STA2/test2

#### plot
midlayers_mCBR %>% 
  ggplot(aes(x = rsp_index, y = depth_from_surface, group = sample_id, color = CBR_id)) +
  geom_path(linewidth = 0.75) +
  scale_color_manual(values = CBR_colors) +
  facet_grid(test_area~test_id, switch = "x") +
  scale_y_continuous(trans = "reverse", limits = c(200,0)) +
  scale_x_continuous(position = "top") +
  xlab("RSP Index at Surface (0-6 inches)") +
  ylab("Depth from Surface (mm)") +
  labs(color = "Corresponding\nCBR") +
  theme_bw()

## average for each time point (test #) in 50-200
mid_method1 <- midlayers_mCBR %>% 
  select(c(sample_id, depth_from_surface, rsp_index)) %>% 
  pivot_wider(names_from = sample_id, values_from = rsp_index) %>% 
  arrange(depth_from_surface) %>% 
  mutate(STA1_test0 = round(rowMeans(across(starts_with("STA1_test0")), na.rm=TRUE))) %>% 
  mutate(STA2_test0 = round(rowMeans(across(starts_with("STA2_test0")), na.rm=TRUE))) %>% 
  mutate(STA1_test1 = round(rowMeans(across(starts_with("STA1_test1")), na.rm=TRUE))) %>% 
  mutate(STA2_test1 = round(rowMeans(across(starts_with("STA2_test1")), na.rm=TRUE))) %>%
  mutate(STA1_test2 = round(rowMeans(across(starts_with("STA1_test2")), na.rm=TRUE))) %>% 
  mutate(STA2_test2 = round(rowMeans(across(starts_with("STA2_test2")), na.rm=TRUE))) %>%
  mutate(STA1_test3 = round(rowMeans(across(starts_with("STA1_test3")), na.rm=TRUE))) %>% 
  mutate(STA2_test3 = round(rowMeans(across(starts_with("STA2_test3")), na.rm=TRUE))) %>%
  mutate(STA1_test4 = round(rowMeans(across(starts_with("STA1_test4")), na.rm=TRUE))) %>% 
  mutate(STA2_test4 = round(rowMeans(across(starts_with("STA2_test4")), na.rm=TRUE))) %>%
  select(c(STA1_test0, STA2_test0, STA1_test1, STA2_test1, STA1_test2, STA2_test2, STA1_test3, STA2_test3, STA1_test4, STA2_test4, depth_from_surface)) %>% 
  pivot_longer(cols = c(STA1_test0, STA2_test0, STA1_test1, STA2_test1, STA1_test2, STA2_test2, STA1_test3, STA2_test3, STA1_test4, STA2_test4), names_to = "station_test", values_to = "rsp_index") %>% 
  mutate(station = substr(station_test, 1, 4)) %>% 
  mutate(test = substr(station_test, 6, 10)) %>% 
  mutate(test = ifelse(test == "test0", "Test 0", test)) %>% 
  mutate(test = ifelse(test == "test1", "Test 1", test)) %>% 
  mutate(test = ifelse(test == "test2", "Test 2", test)) %>% 
  mutate(test = ifelse(test == "test3", "Test 3", test)) %>% 
  mutate(test = ifelse(test == "test4", "Test 4", test)) %>% 
  mutate(test = ifelse(test == "test5", "Test 5", test))

#### plot
mid_method1 %>% 
  ggplot(aes(x = rsp_index, y = depth_from_surface, group = station_test, color = test)) +
  geom_path(linewidth = 0.75) +
  scale_color_manual(values = test_colors) +
  facet_grid(~station, switch = "x") +
  scale_y_continuous(trans = "reverse", limits = c(200,0)) +
  scale_x_continuous(position = "top") +
  xlab("Average RSP Index at Surface (50-200mm)") +
  ylab("Depth from Surface (mm)") +
  labs(color = "Corresponding\nCBR Timepoint") +
  theme_bw()

## method 2
mid_method2 <- midlayers_mCBR %>% 
  select(c(sample_id, depth_from_surface, rsp_index)) %>% 
  pivot_wider(names_from = sample_id, values_from = rsp_index) %>% 
  arrange(depth_from_surface) %>% 
  mutate(STA1_test0_CBR1 = round(rowMeans(across(starts_with("STA1_test0_CBR1")), na.rm=TRUE))) %>% 
  mutate(STA1_test0_CBR2 = round(rowMeans(across(starts_with("STA1_test0_CBR2")), na.rm=TRUE))) %>%
  mutate(STA1_test0_CBR3 = round(rowMeans(across(starts_with("STA1_test0_CBR3")), na.rm=TRUE))) %>%
  mutate(STA2_test0_CBR1 = round(rowMeans(across(starts_with("STA2_test0_CBR1")), na.rm=TRUE))) %>% 
  mutate(STA2_test0_CBR2 = round(rowMeans(across(starts_with("STA2_test0_CBR2")), na.rm=TRUE))) %>%
  mutate(STA2_test0_CBR3 = round(rowMeans(across(starts_with("STA2_test0_CBR3")), na.rm=TRUE))) %>%
  mutate(STA1_test1_CBR1 = round(rowMeans(across(starts_with("STA1_test1_CBR1")), na.rm=TRUE))) %>% 
  mutate(STA1_test1_CBR2 = round(rowMeans(across(starts_with("STA1_test1_CBR2")), na.rm=TRUE))) %>%
  mutate(STA1_test1_CBR5 = round(rowMeans(across(starts_with("STA1_test1_CBR5")), na.rm=TRUE))) %>%
  mutate(STA2_test1_CBR1 = round(rowMeans(across(starts_with("STA2_test1_CBR1")), na.rm=TRUE))) %>% 
  mutate(STA2_test1_CBR2 = round(rowMeans(across(starts_with("STA2_test1_CBR2")), na.rm=TRUE))) %>%
  mutate(STA2_test1_CBR3 = round(rowMeans(across(starts_with("STA2_test1_CBR3")), na.rm=TRUE))) %>%
  mutate(STA1_test2_CBR2 = round(rowMeans(across(starts_with("STA1_test2_CBR2")), na.rm=TRUE))) %>% 
  mutate(STA1_test2_CBR3 = round(rowMeans(across(starts_with("STA1_test2_CBR3")), na.rm=TRUE))) %>%
  mutate(STA1_test2_CBR4 = round(rowMeans(across(starts_with("STA1_test2_CBR4")), na.rm=TRUE))) %>%
  mutate(STA2_test2_CBR2 = round(rowMeans(across(starts_with("STA2_test2_CBR2")), na.rm=TRUE))) %>% 
  mutate(STA2_test2_CBR3 = round(rowMeans(across(starts_with("STA2_test2_CBR3")), na.rm=TRUE))) %>%
  mutate(STA2_test2_CBR4 = round(rowMeans(across(starts_with("STA2_test2_CBR4")), na.rm=TRUE))) %>%
  mutate(STA1_test3_CBR1 = round(rowMeans(across(starts_with("STA1_test3_CBR1")), na.rm=TRUE))) %>% 
  mutate(STA1_test3_CBR2 = round(rowMeans(across(starts_with("STA1_test3_CBR2")), na.rm=TRUE))) %>%
  mutate(STA1_test3_CBR4 = round(rowMeans(across(starts_with("STA1_test3_CBR4")), na.rm=TRUE))) %>%
  mutate(STA2_test3_CBR1 = round(rowMeans(across(starts_with("STA2_test3_CBR1")), na.rm=TRUE))) %>% 
  mutate(STA2_test3_CBR2 = round(rowMeans(across(starts_with("STA2_test3_CBR2")), na.rm=TRUE))) %>%
  mutate(STA2_test3_CBR3 = round(rowMeans(across(starts_with("STA2_test3_CBR3")), na.rm=TRUE))) %>%
  mutate(STA1_test4_CBR1 = round(rowMeans(across(starts_with("STA1_test4_CBR1")), na.rm=TRUE))) %>% 
  mutate(STA1_test4_CBR2 = round(rowMeans(across(starts_with("STA1_test4_CBR2")), na.rm=TRUE))) %>%
  mutate(STA1_test4_CBR3 = round(rowMeans(across(starts_with("STA1_test4_CBR3")), na.rm=TRUE))) %>%
  mutate(STA2_test4_CBR1 = round(rowMeans(across(starts_with("STA2_test4_CBR1")), na.rm=TRUE))) %>% 
  mutate(STA2_test4_CBR2 = round(rowMeans(across(starts_with("STA2_test4_CBR2")), na.rm=TRUE))) %>%
  mutate(STA2_test4_CBR3 = round(rowMeans(across(starts_with("STA2_test4_CBR3")), na.rm=TRUE))) %>%
  select(c(STA1_test0_CBR1, STA1_test0_CBR2, STA1_test0_CBR3, STA2_test0_CBR1, STA2_test0_CBR2, STA2_test0_CBR3, STA1_test1_CBR1, STA1_test1_CBR2, STA1_test1_CBR5, STA2_test1_CBR1, STA2_test1_CBR2, STA2_test1_CBR3, STA1_test2_CBR2, STA1_test2_CBR3, STA1_test2_CBR4, STA2_test2_CBR2, STA2_test2_CBR3, STA2_test2_CBR4, STA1_test3_CBR1, STA1_test3_CBR2, STA1_test3_CBR4, STA2_test3_CBR1, STA2_test3_CBR2, STA2_test3_CBR3, STA1_test4_CBR1, STA1_test4_CBR2, STA1_test4_CBR3, STA2_test4_CBR1, STA2_test4_CBR2, STA2_test4_CBR3, depth_from_surface)) %>% 
  pivot_longer(cols = c(STA1_test0_CBR1, STA1_test0_CBR2, STA1_test0_CBR3, STA2_test0_CBR1, STA2_test0_CBR2, STA2_test0_CBR3, STA1_test1_CBR1, STA1_test1_CBR2, STA1_test1_CBR5, STA2_test1_CBR1, STA2_test1_CBR2, STA2_test1_CBR3, STA1_test2_CBR2, STA1_test2_CBR3, STA1_test2_CBR4, STA2_test2_CBR2, STA2_test2_CBR3, STA2_test2_CBR4, STA1_test3_CBR1, STA1_test3_CBR2, STA1_test3_CBR4, STA2_test3_CBR1, STA2_test3_CBR2, STA2_test3_CBR3, STA1_test4_CBR1, STA1_test4_CBR2, STA1_test4_CBR3, STA2_test4_CBR1, STA2_test4_CBR2, STA2_test4_CBR3), names_to = "station_test_CBR", values_to = "rsp_index") %>% 
  mutate(station = substr(station_test_CBR, 1, 4)) %>% 
  mutate(test = substr(station_test_CBR, 6, 10)) %>% 
  mutate(test = ifelse(test == "test0", "Test 0", test)) %>% 
  mutate(test = ifelse(test == "test1", "Test 1", test)) %>% 
  mutate(test = ifelse(test == "test2", "Test 2", test)) %>% 
  mutate(test = ifelse(test == "test3", "Test 3", test)) %>% 
  mutate(test = ifelse(test == "test4", "Test 4", test)) %>% 
  mutate(test = ifelse(test == "test5", "Test 5", test))

mid_method2 %>% 
  ggplot(aes(x = rsp_index, y = depth_from_surface, group = station_test_CBR, color = test)) +
  geom_path(linewidth = 0.75) +
  scale_color_manual(values = test_colors) +
  facet_grid(~station, switch = "x") +
  scale_y_continuous(trans = "reverse", limits = c(200,0)) +
  scale_x_continuous(position = "top") +
  xlab("Average RSP Index at Surface (50-200mm)") +
  ylab("Depth from Surface (mm)") +
  labs(color = "Corresponding\nCBR Timepoint") +
  theme_bw()
```

#### For correlation
```{r}
meanCBR <- cbrdata %>% 
  group_by(station_test) %>% 
  summarize(meanCBR = mean(CBR))

## Method 1: 50-200mm, Margie's CBR avg, and avg RSP across depth
mid_method1_corrval <- mid_method1 %>% #average per test and averaged across depth too
  group_by(station_test) %>% 
  summarize(meanRSP = mean(rsp_index, na.rm = TRUE)) %>% 
  full_join(meanCBR, by = "station_test")

mid_model1 <- lm(meanRSP ~ meanCBR, data = mid_method1_corrval)
mid_r2_1 <- summary(mid_model1)$r.squared

mid_method1_corrval %>% 
  ggplot(aes(x = meanRSP, y = meanCBR)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  annotate("text", x = 35, y = 18, label = paste("R² =", round(mid_r2_1, 2)), size = 5, hjust = 1)

## Method 2: 50-200mm, Margie's CBR, and avg RSP across depth (average the RSPs for each corresponding CBR)
mid_method2_corrval <- mid_method2 %>% 
  group_by(station_test_CBR) %>% 
  summarize(meanRSP = mean(rsp_index, na.rm = TRUE)) %>% 
  full_join(cbrdata, by = "station_test_CBR")

mid_model2 <- lm(meanRSP ~ CBR, data = mid_method2_corrval)
mid_r2_2 <- summary(mid_model2)$r.squared

mid_method2_corrval %>% 
  ggplot(aes(x = meanRSP, y = CBR)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  annotate("text", x = 28, y = 20, label = paste("R² =", round(mid_r2_2, 2)), size = 5, hjust = 1)
```

