---
title: "RSP analysis"
author: "Katie L. Duggan DiDominic"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load packages
```{r}
#install.packages("tidyverse")
library(tidyverse)
#install.packages("NatParksPalettes")
library(NatParksPalettes)
#install.packages("ggpmisc")
library(ggpmisc)
library(ggthemes)
library(lmtest)
```

## Load data
```{r}
rsp_2026 <- read_csv(file = "/Users/u4rrnkld/OneDrive - US Army Corps of Engineers/Documents/RSPtoCBR_correlation/data/rspdata_2026.csv") 

cbr_2026 <- read_csv(file = "/Users/u4rrnkld/OneDrive - US Army Corps of Engineers/Documents/RSPtoCBR_correlation/data/cbrdata_2026.csv")

corrected_rsp_cbr_26 <- left_join(rsp_2026, cbr_2026, by = c("sample_id", "lane", "station", "lane_station"))%>% 
  mutate(correct_lane_station = ifelse(lane_station == "SW_STA9", "SW_STA11", lane_station)) %>% 
  mutate(correct_lane_station = ifelse(lane_station == "SW_STA8", "SW_STA10", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "SW_STA7", "SW_STA09", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "SW_STA6", "SW_STA08", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "SW_STA5", "SW_STA07", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "SW_STA4", "SW_STA06", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "SW_STA3", "SW_STA05", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "SW_STA2", "SW_STA04", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "SW_STA1", "SW_STA03", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "W_STA1", "SW_STA02", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "W_STA2", "SW_STA01", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "SE_STA8", "SE_STA11", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "SE_STA7", "SE_STA10", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "SE_STA6", "SE_STA09", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "SE_STA5", "SE_STA08", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "SE_STA4", "SE_STA07", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "SE_STA3", "SE_STA06", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "SE_STA2", "SE_STA05", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "SE_STA1", "SE_STA04", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "SE_STA0", "SE_STA03", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "E_STA1", "SE_STA02", correct_lane_station)) %>%
  mutate(correct_lane_station = ifelse(lane_station == "E_STA2", "SE_STA01", correct_lane_station)) %>% 
  mutate(correct_sample_id = paste(correct_lane_station, rsp_replicate, sep = "_")) %>%
  mutate(correct_lane = str_extract(correct_lane_station, "^[^_]+")) %>% 
  mutate(correct_station = sub("^[^_]*_", "", correct_lane_station)) %>% 
  select(c(correct_sample_id, correct_lane, correct_station, correct_lane_station, rsp_replicate, rsp_date_time, depth_from_surface, rsp_index, cbr_date, cbr_time, cbr_date_time, hours_post_construction, CBR)) %>% 
  rename(replicate = rsp_replicate) %>% 
  mutate(replicate = ifelse(replicate == 1, "R1", replicate)) %>% 
  mutate(replicate = ifelse(replicate == 2, "R2", replicate)) %>% 
  mutate(replicate = ifelse(replicate == 3, "R3", replicate)) %>% 
  mutate(dist_ramp_end = ifelse(correct_station == "STA01", 7, "")) %>% 
  mutate(dist_ramp_end = ifelse(correct_station == "STA02", 10, dist_ramp_end)) %>%
  mutate(dist_ramp_end = ifelse(correct_station == "STA03", 13, dist_ramp_end)) %>%
  mutate(dist_ramp_end = ifelse(correct_station == "STA04", 16, dist_ramp_end)) %>%
  mutate(dist_ramp_end = ifelse(correct_station == "STA05", 19, dist_ramp_end)) %>%
  mutate(dist_ramp_end = ifelse(correct_station == "STA06", 22, dist_ramp_end)) %>%
  mutate(dist_ramp_end = ifelse(correct_station == "STA07", 25, dist_ramp_end)) %>%
  mutate(dist_ramp_end = ifelse(correct_station == "STA08", 28, dist_ramp_end)) %>%
  mutate(dist_ramp_end = ifelse(correct_station == "STA09", 31, dist_ramp_end)) %>%
  mutate(dist_ramp_end = ifelse(correct_station == "STA10", 34, dist_ramp_end)) %>%
  mutate(dist_ramp_end = ifelse(correct_station == "STA11", 37, dist_ramp_end)) %>% 
  mutate(dist_ramp_end = as.numeric(dist_ramp_end))
```

## Analyze

### Spaghetti plots for all RSP data
```{r}
# Create a small dataframe for the C-17 segments
c17_segment_data <- data.frame(
  x = c(99, 65),
  xend = c(99, 65),
  y = c(0, 250),
  yend = c(250, 400),
  segment_label = "Minimum RSP\nRequired for\nAircraft Load\nof 500,000 lbs")  # label that will show in the legend

c17_segment_data$sample_id <- NA

# Spaghetti Plot
colorblind_colors2 <- c("r1" = "hotpink2", "r2" = "#009E73", "r3" = "goldenrod2") 

# before corrected sample names (e.g., SW_STA0 and W/E lanes)
rsp_2026 %>% 
  ggplot(aes(x = rsp_index, y = depth_from_surface, group = sample_id, color = lane_station)) +
  geom_path(linewidth = 0.75) +
  geom_segment(data = c17_segment_data,
               aes(x = x, xend = xend, y = y, yend = yend),
               color = "black", 
               inherit.aes = FALSE,
               linewidth = 0.75) +
  #scale_color_manual(values = colorblind_colors2) +
  facet_grid(lane~station, switch = "x") + 
  scale_y_continuous(trans = "reverse") +
  scale_x_continuous(position = "top") +
  xlab("RSP Index") +
  ylab("Depth from Surface (mm)") +
  labs(color = "Location (lane/station)") +
  theme_bw() +
  theme(axis.text = element_text(size = 15),
        legend.position = "none",
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        strip.text = element_text(size = 15))

# after corrected sample names (e.g., SW_STA0 and W/E lanes)
corrected_rsp_cbr_26 %>% 
  ggplot(aes(x = rsp_index, y = depth_from_surface, group = correct_sample_id, color = replicate)) +
  geom_path(linewidth = 0.75) +
  geom_segment(data = c17_segment_data,
               aes(x = x, xend = xend, y = y, yend = yend),
               color = "black", 
               inherit.aes = FALSE,
               linewidth = 0.75) +
  scale_color_manual(values = colorblind_colors2) +
  facet_grid(factor(correct_lane, levels = c("SW", "SE"))~correct_station, switch = "x") + 
  scale_y_continuous(trans = "reverse") +
  scale_x_continuous(position = "top") +
  xlab("RSP Index") +
  ylab("Depth from Surface (mm)") +
  labs(color = "Location (lane/station)") +
  theme_bw() +
  theme(axis.text = element_text(size = 15),
        legend.position = "none",
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        strip.text = element_text(size = 15))
```

### Mean RSP for Correlation
```{r}
# Calculate mean across depth
rsp_mean_over_depth <- corrected_rsp_cbr_26 %>%
  group_by(correct_sample_id) %>%
  summarize(mean_rsp = mean(rsp_index)) %>% 
  mutate(correct_lane = str_extract(correct_sample_id, "^[^_]+")) %>% 
  mutate(correct_station = substr(correct_sample_id, 4, 8)) 

corrected_rsp_cbr_26 %>% 
  ggplot(aes(x = rsp_index, y = depth_from_surface, group = correct_sample_id, color = replicate)) +
  geom_path(linewidth = 0.75) +
  geom_point() +
  geom_vline(data = rsp_mean_over_depth, aes(xintercept = mean_rsp), color = "black", linetype = "dashed", linewidth = 1) +
  #scale_linetype_manual(name = "Minimum Required \nRSP for Aircraft Load",
                        #values = c("500,000 lbs" = "solid")) +
  scale_color_manual(values = colorblind_colors2) +
  facet_grid(factor(correct_lane, levels = c("SW", "SE"))~correct_station, switch = "x") + 
  scale_y_continuous(trans = "reverse") +
  scale_x_continuous(position = "top") +
  xlab("RSP Index") +
  ylab("Depth from Surface (mm)") +
  #labs(color = "Corresponding\nCBR") +
  theme_bw() +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        strip.text = element_text(size = 12))

####### plot of mean RSPs (all data) over snow runway surface
rsp_cbr_2026 <- rsp_mean_over_depth %>% 
  select(-c(correct_lane, correct_station)) %>% 
  full_join(corrected_rsp_cbr_26, by = "correct_sample_id")

rsp_cbr_2026 %>% 
  ggplot(aes(x = dist_ramp_end, y = mean_rsp, group = correct_lane_station, color = hours_post_construction)) +
  geom_line(linewidth = 1.25) +
  geom_point(size = 3, aes(shape = replicate)) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dotted") +
  #scale_color_distiller(palette = "BrBG") +
  scale_color_gradientn(colors = c("#082544", "#1E547D", "#79668C", "#DE3C37", "#F2DC7E")) +
  #scale_color_continuous(values = natparks.pals("Yellowstone", 5)) +
  scale_x_continuous(limits = c(0,40), breaks = seq(0, 35, by = 5)) +
  facet_grid(factor(correct_lane, levels = c("SW", "SE"))~.) + 
  xlab("Distance from End (ft)") +
  ylab("RSP mean across depth (0-400mm)") +
  labs(color = "Days Post Construction", shape = "RSP Replicate") +
  theme_bw() +
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        strip.text = element_text(size = 15))
```

#### Correlation with mean RSP from points (10 to 10, CBR to RSP)
```{r}
rsp_means_for_plot <- rsp_cbr_2026 %>% 
  filter(between(depth_from_surface, 50, 200)) #keep 50mm through 200mm

corrected_rsp_cbr_26 %>% 
  filter(between(depth_from_surface, 50, 200)) %>%
  ggplot(aes(x = rsp_index, y = depth_from_surface, group = correct_sample_id, color = replicate)) +
  geom_path(linewidth = 0.75) +
  geom_point() +
  geom_vline(data = rsp_means_for_plot, aes(xintercept = mean_rsp), color = "black", linetype = "dashed", linewidth = 1) +
  #scale_linetype_manual(name = "Minimum Required \nRSP for Aircraft Load",
                        #values = c("500,000 lbs" = "solid")) +
  scale_color_manual(values = colorblind_colors2) +
  facet_grid(factor(correct_lane, levels = c("SW", "SE"))~correct_station, switch = "x") + 
  scale_y_continuous(trans = "reverse") +
  scale_x_continuous(position = "top") +
  xlab("RSP Index") +
  ylab("Depth from Surface (mm)") +
  #labs(color = "Corresponding\nCBR") +
  theme_bw() +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        strip.text = element_text(size = 12))

rsp_mean_filtered <- rsp_means_for_plot %>% #get dataset with 66 RSP values (50-200mm)
  group_by(correct_sample_id) %>% 
  summarize(mean_rsp = mean(mean_rsp)) %>% 
  mutate(correct_lane = str_extract(correct_sample_id, "^[^_]+")) %>% 
  mutate(correct_station = substr(correct_sample_id, 4, 8)) %>% 
  mutate(replicate = substr(correct_sample_id, 10, 10)) %>% 
  mutate(replicate = ifelse(replicate == 1, "R1", replicate)) %>% 
  mutate(replicate = ifelse(replicate == 2, "R2", replicate)) %>% 
  mutate(replicate = ifelse(replicate == 3, "R3", replicate))

cbr_mean <- rsp_means_for_plot %>% 
  group_by(correct_sample_id) %>% 
  summarize(mean_cbr = mean(CBR))
  
means_for_corr_2026 <- full_join(rsp_mean_filtered, cbr_mean, by = "correct_sample_id")
```


## Correlation plot (CBR vs RSP)
#### For new (FY26) data only
```{r}
## correlation model
#linear
corr_lm <- lm(mean_cbr ~ mean_rsp, data = means_for_corr_2026)
corr_lm_r2 <- summary(corr_lm)$r.squared

ggplot(corr_lm, aes(x = .fitted, y = .resid)) +
  geom_point() +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed", size = 1) +
  labs(title = "Residuals vs. Fitted Values Plot (Simple Method)",
       x = "Fitted Values",
       y = "Residuals") +
  theme_minimal()

#exponential
corr_exp <- lm(log(mean_cbr) ~ mean_rsp, data = means_for_corr_2026)
corr_exp_r2 <- summary(corr_exp)$r.squared

#power law
corr_pow = lm(log(mean_cbr) ~ log(mean_rsp), data=means_for_corr_2026)
corr_pow_r2 <- summary(corr_pow)$r.squared

#model equation:
equation_string <- paste0("y = ", 0.4600, "x - ", 3.76)

## plot
ggplot(means_for_corr_2026, aes(x = mean_rsp, y = mean_cbr)) +
  geom_point(aes(color = correct_lane), size = 3) +
  #scale_x_log10() +
  #scale_y_log10() +
  #scale_color_manual(values = STA_colors) + #(use group_colors for the TR)
  #geom_abline(slope = 0.4600, intercept = -3.7572, linetype = "dashed", linewidth = 1) +
  #annotate("text", x = 30, y = 20, label = equation_string, color = "black", size = 5.5) +
  #annotate("text", x = 30, y = 18, label = "R^2 == 0.44", parse = TRUE, color = "black", size = 5.5) +
  xlab("RSP Index") +
  ylab("CBR") +
  xlim(0, 65) + #(making the scale the same helps see that the trend line equation is correct)
  ylim(0, 65) +
  labs(color = "Replicate") +
  theme_bw() +
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.position = "inside",
        legend.position.inside = c(0.1, 0.875),
        strip.text = element_text(size = 15))
```

#### import data from previous year (FY25)
```{r}
means_for_corr_2025 <- read.csv(file = "/Users/u4rrnkld/OneDrive - US Army Corps of Engineers/Documents/RSPtoCBR_correlation/data/means_for_corr_2025.csv") %>% 
  mutate(study_year = "FY25") %>% 
  rename(sample_id = station_test) %>% 
  rename(mean_cbr = CBR) %>% 
  select(c(sample_id, mean_rsp, mean_cbr, study_year))

means_for_corr_2026_yr <- means_for_corr_2026 %>% 
  mutate(study_year = "FY26") %>% 
  rename(sample_id = correct_sample_id) %>% 
  select(c(sample_id, mean_rsp, mean_cbr, study_year))

cumulative_data <- rbind(means_for_corr_2026_yr, means_for_corr_2025)

## correlation and plot
#linear
corrcum_lm <- lm(mean_cbr ~ mean_rsp, data = cumulative_data)
corrcum_lm_r2 <- summary(corrcum_lm)$r.squared

ggplot(corrcum_lm, aes(x = .fitted, y = .resid)) +
  geom_point() +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed", size = 1) +
  labs(title = "Residuals vs. Fitted Values Plot (Simple Method)",
       x = "Fitted Values",
       y = "Residuals") +
  theme_minimal()

#exponential
corrcum_exp <- lm(log(mean_cbr) ~ mean_rsp, data = cumulative_data)
corrcum_exp_r2 <- summary(corrcum_exp)$r.squared

#power law
corrcum_pow = lm(log(mean_cbr) ~ log(mean_rsp), data=cumulative_data)
corrcum_pow_r2 <- summary(corrcum_pow)$r.squared

#model equation:
equation_string <- paste0("y = ", 0.4600, "x - ", 3.76)

## plot
ggplot(cumulative_data, aes(x = mean_rsp, y = mean_cbr)) +
  geom_point(aes(color = study_year), size = 3) +
  #scale_x_log10() +
  #scale_y_log10() +
  #scale_color_manual(values = STA_colors) + #(use group_colors for the TR)
  #geom_abline(slope = 0.4600, intercept = -3.7572, linetype = "dashed", linewidth = 1) +
  #annotate("text", x = 30, y = 20, label = equation_string, color = "black", size = 5.5) +
  #annotate("text", x = 30, y = 18, label = "R^2 == 0.44", parse = TRUE, color = "black", size = 5.5) +
  xlab("RSP Index") +
  ylab("CBR") +
  xlim(0, 65) + #(making the scale the same helps see that the trend line equation is correct)
  ylim(0, 65) +
  labs(color = "Year") +
  theme_bw() +
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.position = "inside",
        legend.position.inside = c(0.1, 0.875),
        strip.text = element_text(size = 15))
```

#### same thing but with FY25 study not averaged (30 RSP-CBR vs. only 10)
```{r}
cbrdata_2025 <- read_csv(file = "/Users/u4rrnkld/OneDrive - US Army Corps of Engineers/Documents/RSPtoCBR_correlation/data/cbrdata.csv") %>% 
  mutate(station_test_cbr = station_test_CBR)

rspdata_2025 <- read_csv(file = "/Users/u4rrnkld/OneDrive - US Army Corps of Engineers/Documents/RSPtoCBR_correlation/data/rspdata.csv")

rspdata_2025 %>% 
  group_by(station_test_cbr) %>% 
  summarize(mean_rsp = mean(rsp_index)) %>% 
  View()
```


